export const ROUTES = {
  HOME: '/',
  COURSES: '/courses',
  MYPAGE: '/mypage',
  STUDY_GROUP: '/study-group',
  STUDY_GROUP_ID: (id: string | number) => `/study-group/${id}`,
  STUDY_GROUP_DETAIL: '/study-group/:id',
  STUDY_GROUP_CREATE: '/study-group/create',
  RECRUITMENT: '/recruitment',
  RECRUITMENT_ID: (id: string | number) => `/recruitment/${id}`,
  RECRUITMENT_DETAIL: '/recruitment/:id',
  RECRUITMENT_CREATE: '/recruitment/create',
  RECRUITMENT_MANAGE: '/recruitment/manage',
  LOGIN: '/auth/login',
  SIGNUP: '/auth/signup',
  FIND_EMAIL: '/auth/find-email',
  FIND_PASSWORD: '/auth/find-password',
} as const
