export const markdownStyles = {
  h1: 'text-2xl font-bold mb-4',
  h2: 'text-xl font-semibold mt-8',
  h3: 'text-lg font-semibold mt-6',
  h4: 'text-base font-semibold mt-4',
  h5: 'text-base font-medium mt-3',
  h6: 'text-sm font-medium mt-3',
  p: 'text-base leading-relaxed mb-6',
  ul: 'list-disc list-inside space-y-1 text-base leading-relaxed mb-6 ml-6 mt-3',
  ol: 'list-decimal list-inside space-y-1 text-base leading-relaxed mb-6 ml-6 mt-3',
  li: 'text-base leading-relaxed',
  img: 'w-full rounded-lg shadow mb-8',
  blockquote:
    'border-l-4 border-blue-500 pl-4 py-2 bg-gray-50 text-gray-700 italic mb-6',
  code: 'bg-gray-100 text-red-600 px-1 py-0.5 rounded text-sm font-mono',
  pre: 'bg-gray-900 text-white p-4 rounded-lg overflow-x-auto mb-6',
  a: 'text-blue-600 hover:text-blue-800 underline',
  strong: 'font-semibold',
  em: 'italic',
  hr: 'border-t border-gray-300 my-8',
  table: 'min-w-full border-collapse border border-gray-300 mb-6',
  th: 'border border-gray-300 bg-gray-100 px-4 py-2 text-left font-semibold',
  td: 'border border-gray-300 px-4 py-2',
  tr: 'hover:bg-gray-50',
}
